# Generated by Django 4.1.6 on 2023-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='_tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
