# Generated by Django 4.1.6 on 2023-04-27 22:56

from django.contrib.staticfiles import finders
from django.core.files import File
from django.db import migrations, models

# The default image for all the foods.
DEFAULT_IMAGE = 'images/default.jpg'


def set_default_image(apps, schema_editor):
    """
    Sets the default image of the foods.
    """

    # Load the Food model
    Foods = apps.get_model('listing', 'Food')
    default_image_path = finders.find(DEFAULT_IMAGE)

    # Open the default image file
    with open(default_image_path, 'rb') as file:
        default_image = File(file)
        # Set the default image for all foods
        # Foods.objects.update(image=default_image)

        for food in Foods.objects.all():
            food.image.save('default-image.jpg', default_image)


class Migration(migrations.Migration):
    dependencies = [
        ('listing', '0003_food_image_alter_food__tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='foods'),
        ),
        migrations.RunPython(set_default_image)
    ]
